certmanager:
  install: false
certmanager-issuer:
  email: CERT_MANAGER_EMAIL
gitlab:
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  task-runner:
    enabled: false
  webservice:
    minReplicas: 1
    maxReplicas: 1
gitlab-runner:
  install: false
global:
  hosts:
    domain: GITLAB_BASE_FQDN
    externalIP: EXTERNAL_LB_IP
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-contour-cluster-issuer
      kubernetes.io/tls-acme: true
      projectcontour.io/ingress.class: contour
minio:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
nginx-ingress:
  enabled: false
  controller:
    minAvailable: 0
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
  defaultBackend:
    minAvailable: 0
    replicaCount: 1
    resources:
      requests:
        cpu: 5m
        memory: 5Mi
prometheus:
  install: false
redis:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
