---
concourse:
  web:
    externalUrl: https://CONCOURSE_URL
web:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "contour"
      cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    hosts:
      - CONCOURSE_URL
    tls:
    - hosts:
      - CONCOURSE_URL
      secretName: concourse-cert


